### ISSUE TITLE
Predictor flexibility

### ISSUE THREAD

**Issue by vic85821** [cmlab-mira/template#24]
The predictor of the current version has no ability to perform the global operations (e.g. save the performance of the whole testing data into a csv file). 

The temporal solution is overriding the `predict` function of the `base_predictor`.

**Comment by peter850706** [comment]
Actually, the predictor can also perform the global operations through its attribute, `predict()` and `_test_step()`; however, you need to overriding `predict()` as you mentioned:
```python
class MyPredictor(BasePredictor):
    def __init__(self):
        self.attr = ... # something you need to record
        ...

    def predict(self):
        ... # do something before predicting
        super().predict()
        ... # do something after predicting

    def _test_step(self, batch):
        # do something during predicting
```
I think the `predict()` in `BasePredictor` aims to handle the model inference so that the users do not need to take care of this part (just need to define `_test_step()`). Other things such as saving the performance of the whole testing data into a csv file can be done by the users.
